### ISSUE TITLE
value = pv1 + pv2 TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by stieler-it** [ITTV-tools/homeassistant-kostalplenticore#12]
My configuration stopped working I think a few days ago. 

Config:
```
sensor:
  - platform: kostal_plenticore
    host: 192.168.178.53
    password: !secret kostal_password
    monitored_conditions:
      - HomeGridPower
      - HomeOwnPower
      - HomePVPower
      - GridPower
      - DCPower
      - PVPower
      - AutarkyDay
      - AutarkyMonth
      - AutarkyTotal
      - AutarkyYear
      - CO2SavingDay
      - CO2SavingMonth
      - CO2SavingTotal
      - CO2SavingYear
      - PV1Power
      - PV1Voltage
      - PV1Current
      - ACFrequency
      - ACL1Current
      - ACL1Power
      - ACL1Voltage
      - ACL2Current
      - ACL2Power
      - ACL2Voltage
      - ACL3Current
      - ACL3Power
      - ACL3Voltage
      - HomeConsumptionDay
      - HomeConsumptionMonth
      - HomeConsumptionTotal
      - HomeConsumptionYear
      - HomeConsumptionFromGridDay
      - HomeConsumptionFromGridMonth
      - HomeConsumptionFromGridTotal
      - HomeConsumptionFromGridYear
      - HomeConsumptionFromPVDay
      - HomeConsumptionFromPVMonth
      - HomeConsumptionFromPVTotal
      - HomeConsumptionFromPVYear
      - HomeConsumptionYieldDay
      - HomeConsumptionYieldMonth
      - HomeConsumptionYieldTotal
      - HomeConsumptionYieldYear
      - OwnConsumptionRateDay
      - OwnConsumptionRateMonth
      - OwnConsumptionRateTotal
      - OwnConsumptionRateYear
```

Error message:
```
2020-12-22 00:16:53 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up kostal_plenticore platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/kostal_plenticore/sensor.py", line 483, in setup_platform
plenticore(
File "/config/custom_components/kostal_plenticore/sensor.py", line 563, in __init__
value = self.getData()
File "/config/custom_components/kostal_plenticore/sensor.py", line 514, in getData
value = pv1 + pv2
TypeError: can only concatenate str (not "int") to str
```

This [line](https://github.com/ITTV-tools/homeassistant-kostalplenticore/blob/master/custom_components/kostal_plenticore/sensor.py#L519) looks a little suspicous to me. If only one of both values is in error state then it always looks like a concatenation of an int with a string. I don't understand what's going on there, though...

**Comment by ITTV-tools** [comment]
You are right that is not correct. I changed it to an "and". Now the error handling should work.

**Comment by ITTV-tools** [comment]
I created a pre release.

**Comment by stieler-it** [comment]
Sorry, I could not have a look at the details but copied the new sensor.py and saw the following in the logs:
```
 File "/config/custom_components/kostal_plenticore/sensor.py", line 505
    """Get sensor data."""
    ^
IndentationError: unexpected indent
```
